name: get_random_from_list
description: An extension method for the List class that retrieves a random element from the list.
version: 0.1.1
homepage: https://github.com/james-alex/get_random_from_list

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

dev_dependencies:
  test: ^1.15.3
